import type { Metadata } from "next";
import { CTA } from "@/components/CTA";
import { TrackLink } from "@/components/TrackLink";
import { services } from "@/lib/content";

export const metadata: Metadata = { title: "Services", description: "Product strategy, UX design, software engineering and platform expertise in one senior team.", alternates: { canonical: "/services" }, openGraph: { title: "Product engineering services", description: "Product strategy, UX design, software engineering and platform expertise in one senior team.", url: "/services" } };

export default function ServicesPage() {
  return <main id="main"><header className="services-hero shell"><div><p className="eyebrow">Product engineering services</p><h1>Five capabilities. <em>One accountable team.</em></h1></div><div className="services-hero-note"><span className="label">How we engage</span><p>Bring us a focused challenge or the full product lifecycle. Senior strategy, design and engineering stay connected from the first decision to the next release.</p><TrackLink className="text-link" href="/contact" event="cta_clicked" eventLabel="services-hero">Shape an engagement <span>↗</span></TrackLink></div></header>
    <div className="service-index-wrap"><nav className="service-index shell" aria-label="Service capabilities">{services.map((service, index) => <a href={`#${service.slug}`} key={service.slug}><span>0{index + 1}</span>{service.name}</a>)}</nav></div>
    <div className="service-flow">{services.map((service, index) => <section className={`service-chapter${service.slug === "product-engineering" ? " service-chapter-core" : ""}`} id={service.slug} key={service.slug}><article className="shell"><header className="service-chapter-head"><span className="index">0{index + 1} / 05</span><div><p className="label">Capability</p><h2>{service.name}</h2></div><div className="service-fit"><p className="label">Best when</p><p>{service.stage}</p><dl><div><dt>Engagement</dt><dd>{service.engagement}</dd></div><div><dt>Indicative pace</dt><dd>{service.duration}</dd></div></dl></div></header><div className="service-chapter-body"><div className="service-marker" aria-hidden="true"><span></span></div><div className="service-lead"><p>{service.summary}</p><TrackLink className="text-link" href={`/services/${service.slug}`} event="service_explored" eventLabel={service.slug}>Explore this service <span>↗</span></TrackLink></div><div className="service-spec"><p className="label">Business outcomes</p><ul>{service.outcomes.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="service-spec"><p className="label">What we deliver</p><ul>{service.deliverables.map((item) => <li key={item}>{item}</li>)}</ul></div></div></article></section>)}</div>
    <CTA title="Not sure which capability you need? Good." context="Start with the business problem. We will help define the right shape of engagement." /></main>;
}
