import type { Metadata } from "next";
import { CTA } from "@/components/CTA";
import { principles } from "@/lib/content";

export const metadata: Metadata = { title: "About", description: "A senior, integrated product team for complex operational products.", alternates: { canonical: "/about" }, openGraph: { title: "About Bluice Technologies", description: "A senior, integrated product team for complex operational products.", url: "/about" } };

const leadership = [{ title: "Product direction", mark: "Frame", text: "A senior product lead stays accountable for the business outcome and the decisions needed to reach it." }, { title: "Experience quality", mark: "Design", text: "Design leadership remains close to research, interaction details and the realities of day-to-day use." }, { title: "Engineering integrity", mark: "Ship", text: "Engineering leadership owns technical direction, release quality and the health of the live product." }];

export default function AboutPage() { return <main id="main"><header className="about-hero about-hero-editorial"><div className="shell about-hero-grid"><div className="about-hero-title"><p className="eyebrow">About Bluice Technologies</p><h1>A senior product team, <em>built for continuity.</em></h1></div><aside><p className="label">Integrated by design</p><p>We work with organisations whose software is essential to daily operations—keeping product, design, and engineering accountable to the same outcome.</p><div className="about-disciplines"><span>Product direction</span><span>Experience quality</span><span>Engineering integrity</span></div></aside></div><div className="about-continuity"><div className="shell"><p className="label">One accountable team</p><p><strong>Business context</strong><span>stays connected to</span><strong>product decisions</strong><span>through</span><strong>live operation.</strong></p></div></div></header>
  <section className="about-thesis about-thesis-light"><div className="shell"><span className="label">Our point of view</span><p className="literata">Dependable products come from clearer decisions made by people who stay close enough to see their consequences.</p></div></section>
  <section className="section shell about-model"><header><p className="eyebrow">The operating model</p><h2>Continuity is a product advantage.</h2><p>Traditional delivery loses context at every handoff. We keep the people framing the problem connected to the people designing, building, and improving the answer.</p></header><div className="model-comparison"><div className="model-row model-row-muted"><span>Separated delivery</span><div><b>Discover</b><i>Handoff</i><b>Design</b><i>Handoff</i><b>Build</b></div></div><div className="model-row model-row-connected"><span>Bluice Technologies team</span><div><b>Frame</b><i>↔</i><b>Design</b><i>↔</i><b>Ship</b></div></div></div></section>
  <section className="section about-leadership"><div className="shell"><header className="about-section-head"><div><p className="eyebrow">Senior involvement</p><h2>Accountability stays visible.</h2></div><p>The disciplines work as one unit, but each leadership responsibility remains explicit from direction through live operation.</p></header><div className="leadership-ledger">{leadership.map((role, index) => <article key={role.title}><span className="index">0{index + 1}</span><span className="role-mark">{role.mark}</span><h3>{role.title}</h3><p>{role.text}</p></article>)}</div></div></section>
  <section className="section shell about-principles"><header><p className="eyebrow">How we work</p><h2>Three rules for consequential product work.</h2></header><div>{principles.map(([title, text], index) => <article key={title}><span className="index">0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <CTA title="Work directly with the people responsible for the outcome." context="Tell us what the product needs to change for the business and its users." /></main>; }
