export const services = [
  {
    slug: "product-strategy",
    name: "Product strategy",
    summary: "Turn competing business needs into a product direction your team can execute.",
    outcomes: ["Opportunity framing", "Validated product roadmap", "Investment case"],
    deliverables: ["Stakeholder research", "Product brief", "Prioritised roadmap", "Success measures"],
    stage: "When the problem is important but the path is not yet clear.",
    engagement: "Focused discovery or direction sprint",
    duration: "Typically 3–6 weeks",
  },
  {
    slug: "ux-ui-design",
    name: "UX & UI design",
    summary: "Make complex workflows legible, efficient and ready for real operating conditions.",
    outcomes: ["Faster task completion", "Lower support demand", "Higher adoption"],
    deliverables: ["Service blueprint", "Prototypes", "Design system", "Usability evidence"],
    stage: "When users understand the value but struggle with the experience.",
    engagement: "Embedded design track or focused redesign",
    duration: "Typically 4–10 weeks",
  },
  {
    slug: "product-engineering",
    name: "Product engineering",
    summary: "Ship dependable web and mobile products with product, design and engineering in one team.",
    outcomes: ["Predictable releases", "Lower operating risk", "A maintainable product"],
    deliverables: ["Technical design", "Production software", "Quality automation", "Release operations"],
    stage: "When you need to move from validated direction to a resilient product.",
    engagement: "Product squad or phased build",
    duration: "Usually 12+ weeks",
  },
  {
    slug: "cloud-platform",
    name: "Cloud & platform",
    summary: "Build the foundations that let product teams release safely and scale deliberately.",
    outcomes: ["Stable operations", "Shorter release cycles", "Clear cost controls"],
    deliverables: ["Platform architecture", "Delivery pipelines", "Observability", "Security controls"],
    stage: "When product demand is outgrowing the current technical foundation.",
    engagement: "Platform assessment or implementation team",
    duration: "Typically 6–16 weeks",
  },
  {
    slug: "continuous-evolution",
    name: "Continuous evolution",
    summary: "Improve live products through measured changes rather than periodic rewrites.",
    outcomes: ["Compounding product gains", "Reduced technical debt", "Senior continuity"],
    deliverables: ["Product analytics", "Experiment backlog", "Incremental releases", "Operational reviews"],
    stage: "When a live product needs a steady senior team to keep improving it.",
    engagement: "Senior retained product squad",
    duration: "Quarterly delivery cadence",
  },
];

export const principles = [
  ["Clarity before velocity", "A faster team moving in the wrong direction only creates more rework."],
  ["Evidence over theatre", "Decisions are tied to user behaviour, operating constraints and measurable outcomes."],
  ["Senior people stay close", "The people shaping the work remain accountable through delivery."],
];
