export const regions = {
  IN: { name: "India", currency: "INR", symbol: "₹", marketLine: "India delivery · Global product teams", footerLine: "India · Global delivery", terms: "Visitors in India retain any mandatory rights available under Indian law. Website enquiries and proposals remain subject to a separate written services agreement.", privacy: "For people in India, our handling of digital personal data is informed by the Digital Personal Data Protection Act, 2023, as its provisions apply.", authority: "Ministry of Electronics and Information Technology", authorityUrl: "https://www.meity.gov.in/static/uploads/2024/02/Digital-Personal-Data-Protection-Act-2023.pdf" },
  US: { name: "United States", currency: "USD", symbol: "$", marketLine: "United States market · Global delivery", footerLine: "United States · Global delivery", terms: "Visitors in the United States retain mandatory rights available under applicable federal and state law. A signed services agreement defines the governing terms for client work.", privacy: "For people in the United States, rights can vary by state. Where applicable, requests may include access, correction, deletion, or opting out of certain sharing; California residents may have rights under the CCPA as amended by the CPRA.", authority: "Federal Trade Commission privacy guidance", authorityUrl: "https://www.ftc.gov/business-guidance/privacy-security" },
  GB: { name: "United Kingdom", currency: "GBP", symbol: "£", marketLine: "United Kingdom market · Global delivery", footerLine: "United Kingdom · Global delivery", terms: "Visitors in the United Kingdom retain mandatory rights available under UK law. Nothing in these website terms limits rights that cannot lawfully be excluded.", privacy: "For people in the United Kingdom, applicable rights may include access, correction, erasure, restriction, objection, and data portability under the UK GDPR and Data Protection Act 2018.", authority: "Information Commissioner’s Office", authorityUrl: "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/" },
  AE: { name: "United Arab Emirates", currency: "AED", symbol: "AED", marketLine: "UAE market · Global delivery", footerLine: "United Arab Emirates · Global delivery", terms: "Visitors in the United Arab Emirates retain mandatory rights available under UAE law. Client engagements are governed by their signed services agreement.", privacy: "For people in the UAE, applicable rights may include access, correction, deletion, restriction, objection, and data portability under Federal Decree-Law No. 45 of 2021, subject to its scope and exceptions.", authority: "UAE Legislation platform", authorityUrl: "https://uaelegislation.gov.ae/en/legislations/1972" },
  SG: { name: "Singapore", currency: "SGD", symbol: "S$", marketLine: "Singapore market · Global delivery", footerLine: "Singapore · Global delivery", terms: "Visitors in Singapore retain mandatory rights available under Singapore law. A separate signed agreement governs the scope and terms of client services.", privacy: "For people in Singapore, personal data is handled with reference to the Personal Data Protection Act 2012, including its rules for collection, use, disclosure, access, correction, protection, and retention.", authority: "Personal Data Protection Commission", authorityUrl: "https://www.pdpc.gov.sg/overview-of-pdpa/the-legislation/personal-data-protection-act" },
} as const;

export type RegionCode = keyof typeof regions;
